title: Muhammad Wildan Putra Aldi # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have almost 2 years experience in the field of data, from college 
  to a career as a Big Data Developer, BI Developer, and Data Scientist.
  In this site I will publish blogs (tutorials, research, and how to ...) 
  and stories about projects that I have done.
  <br><br>
  <a href="https://www.linkedin.com/in/wildanputra/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-152704361-1 # your Google Analytics tracking ID here
